--FORAM DEFINIDOS COMO INT PQ NÃO ACEITA INT8

CREATE TABLE ESCOLA(
  ESCOLA_ID INT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(100),
  CNPJ VARCHAR(13),
)

CREATE TABLE TURMA(
  TURMA_ID INT,
  NOME_TURMA VARCHAR(50),
  ESCOLA_ID INT,

  PRIMARY KEY(TURMA_ID),
  FOREIGN KEY (ESCOLA_ID) REFERENCES ESCOLA(ESCOLA_ID)
);

CREATE TABLE USUARIO (
 USUARIO_ID INT PRIMARY KEY,
 LOGIN VARCHAR(30),
 SENHA VARCHAR(30),
 STATUS VARCHAR(30),
 LOGADO BIT, --BOOLEAN NO POSTGREESQL
 DATA_ULTIMO_ACESSO TIMESTAMP,
 DATA_CADASTRO DATE

)

CREATE TABLE ALUNO (
   ALUNO_ID INT,
   NOME VARCHAR(30),
   TELEFONE VARCHAR(20),
   CPF VARCHAR(11),
   NIVEL VARCHAR(60),
   OCUPADO BIT, --BOOLEAN NO POSTGREESQL
   TEMPO_USO TIME,
   TEMPO_RESTANTE TIME,
   TURMA_ID INT,
   USUARIO_ID INT

   PRIMARY KEY (ALUNO_ID),
   FOREIGN KEY (TURMA_ID) REFERENCES TURMA(TURMA_ID),

)


ALTER TABLE ALUNO
ADD FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);


--INSERTS
INSERT INTO USUARIO VALUES (1,'edu', '123', '-', 0, DEFAULT, DEFAULT);
INSERT INTO ESCOLA VALUES (1, 'ENGLISH CLASS', '4389484344');
INSERT INTO TURMA VALUES (1, 'TURMA_DO_ZEQUINHA', 1);
INSERT INTO ALUNO VALUES (1, 'Eduardo', '11-95086-7077', '45654554565', '---', 0, DEFAULT, DEFAULT, 1,1);


